apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: faas-cli-build
spec:
  description: >-
    This task create a build directory for the given function template by using method called shrinkwrap.
  params:
    - name: FAAS_CLI_IMAGE
      default: openfaas/faas-cli:latest
    - name: pathToFunctionDefinitionFile
      default: ./stack.yaml
  workspaces:
    - name: git-source
      description: Holds the context of the function template
  steps:
    - name: faas-cli-build
      workingDir: $(workspaces.git-source.path)
      image: $(params.FAAS_CLI_IMAGE)
      command:
      - sh
      - -c
      - "faas-cli build -f $(params.pathToFunctionDefinitionFile) --shrinkwrap"
