apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-manifest
spec:
  workspaces:
    - name: git-source
      description: The git repo
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
    - name: imageUrl
      description: Image name including repository
    - name: imageTag
      description: Image tag
      default: "latest"
    - name: imageDigest
      description: Digest of the image to be used.
    - name: argoAppName
      default: "hello-function"
  steps:
    - name: update-yaml
      image: alpine
      workingDir: $(workspaces.git-source.path)
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;__IMAGE__;$(params.imageUrl):$(params.imageTag);g"
        - "-e"
        - "s;__DIGEST__;$(params.imageDigest);g"
        - "$(params.pathToYamlFile)"
    - name: commit-push-changes-gitops
      image: alpine/git:v2.26.2
      workingDir: "$(workspaces.git-source.path)"
      script: |
        #!/usr/bin/env sh
        set -e
        git config --global user.email "tekton@tekton.dev"
        git config --global user.name "Tekton Pipeline"
        git add .
        git remote -v
        git status
        git commit -m "[tekton] updating image to $(params.imageDigest)"
        git push origin HEAD:master
